spring.application.name=RE_FORM_Shop_2605

spring.config.import=optional:file:.env[.properties]

#spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Seoul

# ----- database Connection (MariaDB) -----
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://localhost:3306/reform_shop_2605
spring.datasource.username=admin
spring.datasource.password=0507

# file upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=C:/Users/paulkim/Desktop/UpLoad
spring.servlet.multipart.max-request-size=30MB
spring.servlet.multipart.max-file-size=10MB

# redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

# ----- Log4j2 logging Levels -----
logging.level.org.springframework=info
logging.level.org.example.reform_shop_2605=debug

# ----- Console log pattern -----
logging.level.org.mybatis=debug
logging.level.java.sql=debug

# logging pattern
logging.pattern.console=%clr(%-5level){green} %clr(%logger{36}.%M\\(\\)){cyan}: %msg%n

# ----- spring security logging config -----
logging.level.org.springframework.security=info

# jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

# mybatis
# 매퍼 파일의 위치 (resources/mapper 폴더 내의 모든 xml 인식)
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
# 카멜 케이스 자동 매핑
mybatis.configuration.map-underscore-to-camel-case=true

# 애플리케이션 시작 시 전체 경로 목록을 볼 수 있는 설정
spring.mvc.log-request-details=true

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# PGVector용 PostgreSQL
spring.datasource.postgres.url=jdbc:postgresql://localhost:5432/reform_vector
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=postgres
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

# Spring AI PGVector
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE

# Toss Payments
toss.client-key=test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm
toss.secret-key=test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6
toss.url.confirm=https://api.tosspayments.com/v1/payments/confirm

# Spring Batch
spring.batch.jdbc.initialize-schema=always